name: CD - Deploy crud-gateway

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and push
        run: |
          chmod +x ci/build-publish.sh
          USERNAME=mycodeschool \
          REPO=crud-auth-api \
          TAG=${{ env.BUILD_NUMBER }} \
          ci/build-publish.sh ./

#  update-docker-compose:
#    runs-on: ubuntu-latest
#    steps:
      - name: Checkout other repository
        uses: actions/checkout@v2
        with:
          repository: 'mycodeschool-projecs/crud-docker-files'
          token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          path: 'crud-docker-files'

      - name: Update and commit app version in docker-compose.yml in other repository
        run: |
          cd crud-docker-files/
          echo -e "Current ./docker-compose.yaml\n$(cat docker-compose.yaml)"
          sed -i -E 's_(mycodeschool/crud-gateway:)([^"]*)_\1'${{ env.BUILD_NUMBER }}'_' docker-compose.yaml
          echo -e "Updated ./docker-compose.yaml\n$(cat docker-compose.yaml)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "new app version: ${{ env.BUILD_NUMBER }}"
          git push origin HEAD:master


#      - name: Checkout crud-k8s-files repository
#        uses: actions/checkout@v2
#        with:
#          repository: 'mycodeschool-projecs/crud-k8s-files'
#          token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
#          path: 'crud-k8s-files'
#
#      - name: Update and commit app version in deployment-kube-land.yml in other repository
#        run: |
#          cd crud-k8s-files/
#          echo -e "Current ./deployment-kube-land.yaml\n$(cat deployment-kube-land.yaml)"
#          sed -i -E 's_(mycodeschool/crud-auth-api:)([^"]*)_\1'${{ env.BUILD_NUMBER }}'_' deployment-kube-land.yaml
#          echo -e "Updated ./deployment-kube-land.yaml\n$(cat deployment-kube-land.yaml)"
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add .
#          git commit -m "new app version: ${{ env.BUILD_NUMBER }}"
#          git push origin HEAD:master
